services:
  - type: web
    name: hrms-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:migrate && npm run db:seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000